Add wordle, a game, implemented in rust, from https://github.com/conradludgate/wordle. Since upstream is unversioned / untagged, this gets 0.0.
Sadly, even though it builds, it doesn't run; TODO says:

	Debug and fix the issue causing

	   Error: could not determine local timezone

	   Caused by:
	       The system's UTC offset could not be determined

	   Location:
	       src/bin/wordle/game.rs:40:47

I've tried to look around, but have failed to find what the
root problem is; assistance welcome.