add package gcc7snapshot version 20160911
The GNU Compiler Collection (GCC) includes front ends for C, C++, Objective-C,
Fortran, Java, and Go, as well as libraries for these languages (libstdc++,
libgcj,...).

Changes since the GCC 6.0 series:

Caveats

    The non-standard C++0x type traits has_trivial_default_constructor, has_trivial_copy_constructor and has_trivial_copy_assign have been removed.

General Optimizer Improvements
New Languages and Language specific improvements
C family

    GCC 6's C and C++ frontends were able to offer suggestions for misspelled field names:

        spellcheck-fields.cc:52:13: error: 'struct s' has no member named 'colour'; did you mean 'color'?
           return ptr->colour;
                       ^~~~~~

    GCC 7 greatly expands the scope of these suggestions. Firstly, it adds fix-it hints to such suggestions:

        spellcheck-fields.cc:52:13: error: 'struct s' has no member named 'colour'; did you mean 'color'?
           return ptr->colour;
                       ^~~~~~
                       color

    The suggestions now cover many other things, such as misspelled function names:

        spellcheck-identifiers.c:11:3: warning: implicit declaration of function 'gtk_widget_showall'; did you mean 'gtk_widget_show_all'? [-Wimplicit-function-declaration]
           gtk_widget_showall (w);
           ^~~~~~~~~~~~~~~~~~
           gtk_widget_show_all

    misspelled macro names and enum values:

        spellcheck-identifiers.cc:85:11: error: 'MAX_ITEM' undeclared here (not in a function); did you mean 'MAX_ITEMS'?
         int array[MAX_ITEM];
                   ^~~~~~~~
                   MAX_ITEMS

    misspelled type names:

        spellcheck-typenames.c:7:14: error: unknown type name 'singed'; did you mean 'signed'?
         void test (singed char e);
                    ^~~~~~
                    signed

    and, in the C frontend, named initializers:

        test.c:7:20: error: 'struct s' has no member named 'colour'; did you mean 'color'?
         struct s test = { .colour = 3 };
                            ^~~~~~
                            color

    The preprocessor can now offer suggestions for misspelled directives, e.g.:

        test.c:5:2: error:invalid preprocessing directive #endfi; did you mean #endif?
         #endfi
          ^~~~~
          endif

    Warnings about format strings now underline the pertinent part of the string, and can offer suggested fixes. In some cases, the pertinent argument is underlined.

        test.c:51:29: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Wformat=]
           printf ("foo: %d  bar: %s baz: %d", 100, i + j, 102);
                                  ~^                ~~~~~
                                  %d

C

    The C front end now supports type names _FloatN for floating-point types with IEEE interchange formats and _FloatNx for floating-point types with IEEE extended formats. These type names come from ISO/IEC TS 18661-3:2015.

    The set of types supported depends on the target for which GCC is configured. Most targets support _Float32, _Float32x and _Float64. _Float128 is supported on targets where IEEE binary128 encoding was already supported as long double or __float128. _Float64x is supported on targets where a type with either binary128 or Intel extended precision format is available.

    Constants with these types are supported using suffixes fN, FN, fNx and FNx (e.g., 1.2f128 or 2.3F64x). Macros such as FLT128_MAX are defined in <float.h> if __STDC_WANT_IEC_60559_TYPES_EXT__ is defined before it is included.

    These new types are always distinct from each other and from float, double and long double, even if they have the same encoding. Complex types such as _Complex _Float128 are also supported.

    Type-generic built-in functions such as __builtin_isinf support the new types, and the following type-specific built-in functions have versions (suffixed fN or fNx) for the new types: __builtin_copysign, __builtin_fabs, __builtin_huge_val, __builtin_inf, __builtin_nan, __builtin_nans.

C++

    The C++ frontend will now provide fix-it hints for some missing semicolons, allowing for automatic fixes by IDEs:

        test.cc:4:11: error: expected ';' after class definition
         class a {}
                   ^
                   ;

Runtime Library (libstdc++)

    Experimental support for C++17, including the following new features:
        std::string_view;
        std::any, std::optional, and std::variant;
        std::invoke, std::is_callable, and std::is_nothrow_callable;
        std::is_swappable, and std::is_nothrow_swappable;
        std::apply, and std::make_from_tuple;
        std::void_t, std::bool_constant, std::conjunction, std::disjunction, and std::negation;
        Mathematical Special Functions;
        std::chrono::floor, std::chrono::ceil, std::chrono::round, and std::chrono::abs;
        std::clamp;
        std::shared_ptr<T>::weak_type, std::enable_shared_from_this<T>::weak_from_this(), and std::owner_less<void>;
    Thanks to Daniel Krügler, Tim Shen, Edward Smith-Rowland, and Ville Voutilainen for work on the C++17 support.
    A new power-of-two rehashing policy for use with the _Hashtable internals, thanks to François Dumont.

Fortran

    Support for a number of legacy vendor extensions with new flags:
        -fdec-structure - Support for DEC STRUCTURE and UNION.
        -fdec-intrinsic-ints - Support for new integer intrinsics such as degree-valued trig functions (like TAND) and COTAN.
        -fdec - Enable the -fdec family of extensions.
    New flag -finit-derived to control default initialization of derived-type variables.

libgccjit

The libgccjit API gained support for marking calls as requiring tail-call optimization via a new entrypoint: gcc_jit_rvalue_set_bool_require_tail_call.

libgccjit performs numerous checks at the API boundary, but if these succeed, it previously ignored errors and other diagnostics emitted within the core of GCC, and treated the compile of a gcc_jit_context as having succeeded. As of GCC 7 it now ensures that if any diagnostics are emitted, they are visible from the libgccjit API, and that the the context is flagged as having failed.
New Targets and Target Specific Improvements
Operating Systems
Other significant improvements

    -fverbose-asm previously emitted information on the meanings of assembly expressions. This has been extended so that it now also prints comments showing the source lines that correspond to the assembly, making it easier to read the generated assembly (especially with larger functions). For example, given this C source file:

        int test (int n)
        {
          int i;
          int total = 0;

          for (i = 0; i < n; i++)
            total += i * i;
          return total;
        }

    -fverbose-asm now gives output similar to this for the function body (when compiling for x86_64, with -Os):

               .text
               .globl  test
               .type   test, @@function
        test:
        .LFB0:
               .cfi_startproc
        # example.c:4:   int total = 0;
               xorl    %eax, %eax      # <retval>
        # example.c:6:   for (i = 0; i < n; i++)
               xorl    %edx, %edx      # i
        .L2:
        # example.c:6:   for (i = 0; i < n; i++)
               cmpl    %edi, %edx      # n, i
               jge     .L5     #,
        # example.c:7:     total += i * i;
               movl    %edx, %ecx      # i, tmp92
               imull   %edx, %ecx      # i, tmp92
        # example.c:6:   for (i = 0; i < n; i++)
               incl    %edx    # i
        # example.c:7:     total += i * i;
               addl    %ecx, %eax      # tmp92, <retval>
               jmp     .L2     #
        .L5:
        # example.c:10: }
               ret
               .cfi_endproc

    A new option -fdiagnostics-parseable-fixits allows for fix-it hints to be emitted in a machine-readable form, suitable for consumption by IDEs. For example, given:

        spellcheck-fields.cc:52:13: error: 'struct s' has no member named 'colour'; did you mean 'color'?
           return ptr->colour;
                       ^~~~~~
                       color

    it will emit:

        fix-it:"spellcheck-fields.cc":{52:13-52:19}:"color"

    The gcc and g++ driver programs will now provide suggestions for misspelled arguments to command-line options.

        $ gcc -c test.c -ftls-model=global-dinamic
        gcc: error: unknown TLS model 'global-dinamic'
        gcc: note: valid arguments to '-ftls-model=' are: global-dynamic initial-exec local-dynamic local-exec; did you mean 'global-dynamic'?

    The compiler will now provide suggestions for misspelled parameters.

        $ gcc -c test.c --param max-early-inliner-iteration=3
        cc1: error: invalid --param name 'max-early-inliner-iteration'; did you mean 'max-early-inliner-iterations'?

    GCC has gained an internal unit-testing framework, allowing for more detailed testing of its implementation details.