zbar: Update to 0.23.1
Please note that this update is broken and the build fails with:

 | Making all in .
 |   CC       zbarimg/zbarimg-zbarimg.o
 | zbarimg/zbarimg.c:43:10: fatal error: ../zbar/gettext.h: No such file or directory
 |  #include "../zbar/gettext.h"
 |           ^~~~~~~~~~~~~~~~~~~
 | compilation terminated.
 | *** [zbarimg/zbarimg-zbarimg.o] Error code 1

(also documented in TODO.)

Changes:
0.23.1
------
  * Add i18n translation support and add a pt_BR translation
  * Change default to autodetect python and gtk versions
  * Improve tests and builds on travisCI
  * Some documentation updates
  * Add support for binary data extraction
  * Add support for raw decoding without charset conversions
  * Add one shot scanning mode
  * Improved OSX and iphone support
  * Fix help messages
  * Fix some makefile issues
  * Fix error detection in video4linux read
  * Fix pkgconfig for zbar-qt5
  * Fix a double-free condition