Update yed to 3.25
yEd 3.25 - Changes Since 3.24
General

    The JREs that come with the Windows and Linux installers have been updated to OpenJDK 23.0.1. The JRE that comes with the macOS installer has been updated to OpenJDK 21.0.5.

Improvements

    Improved and corrected import support for the GraphML file format variant used by yEd Live.
    Added support for relative file path arguments when starting yEd from command line.

Bugfixes

    Fixed a problem with the native file chooser on operating systems without TrueType fonts.
    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.24 - Changes Since 3.23.2
General

    The JREs that come with the Windows and Linux installers have been updated to OpenJDK 22.0.1. The JRE that comes with the macOS installer has been updated to OpenJDK 21.0.3.

Improvements

    When dragging an edge template from yEd's palette into yEd's editor area, a preview of said template is now displayed during the drag gesture.

Bugfixes

    Fixed file chooser dialog freeze when opening the native file chooser from yEd's welcome screen on macOS.
    Fixed exception that sometimes happened when quitting yEd on macOS.
    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.23.2 - Changes Since 3.23.1
General

    The JREs that come with the Windows, macOS, and Linux installers have been updated to OpenJDK 20.0.2.

Improvements

    Improved and corrected import support for the GraphML file format variants of our commercial yFiles diagramming libraries yFiles for Java 3.x, yFiles for JavaFX, yFiles.NET, yFiles WPF, and yFiles for HTML.
    Added support for importing node symbols with yEd's properties mapper. [Q&A 9287], [Q&A 9335]

Bugfixes

    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.23.1 - Changes Since 3.23
Bugfixes

    Fixed an error that occurred on Windows and macOS operating systems when copying (parts of) diagrams to the system clipboard.

yEd 3.23 - Changes Since 3.22
New Features

    Added new Auto Alignment tool that can be used to snap nodes to the same x- or y-coordinate.

Improvements

    Organic layout now supports integrated edge labeling and directed edges for substructures.
    Circular layout now supports star substructures.
    Added node types as an additional optimization criterion to the Radial layout algorithm. Nodes of the same type are more likely to be placed next to each other.
    Tabular layout now supports node arrangements that minimize the overall edge length.

Bugfixes

    Many bugfixes great and small.

yEd 3.22 - Changes Since 3.21.1
New Features

    Added new Compact Disk layout algorithm that places nodes tightly together.

Improvements

    Organic layout now supports group and tree substructures in addition to chains, stars, circles, and parallel substructures.
    Added new strategies for handling node labels to the Circular and Radial layout algorithms.
    Added new edge routing options to the Circular and Radial layout algorithms.
    Added node types as an additional optimization criterion to the Balloon layout algorithm. Nodes of the same type are more likely to be placed next to each other.

Bugfixes

    Stepping through layout settings with the tab key now selects editable values. [Q&A 23479]
    Many bugfixes great and small.

yEd 3.21.1 - Changes Since 3.21
Bugfixes

    Fixed an error that occurred after changing the display language in yEd.
    Fixed an error that occurred on Windows and macOS operating systems when copying (parts of) diagrams to the system clipboard.

yEd 3.21 - Changes Since 3.20.1
General

    The JREs that come with the Windows, macOS, and Linux installers have been updated to OpenJDK 15.0.2.

New Features

    Added node types as an additional optimization criterion to major layout algorithms. Nodes of the same type are more likely to be placed next to each other.
    Added new clustering implementations for the organic layout algorithm.

Improvements

    Improved edge routing for the orthogonal/polyline edge routing algorithm. The algorithm now tries to preserve existing orthogonal routes as much as possible.

Bugfixes

    Fixed problems with native file chooser dialogs on Windows.
    Fixed regression that prevented layout algorithms to properly connect edges to the visual bounds of nodes. [Q&A 21678], [Q&A 22046]
    Fixed regression that prevented pasting of nodes that were copied from inside a closed group node.
    Fixed inconsistent ordering of palette sections in the 'Add to Palette' context menu. [Q&A 19997]
    Fixed selection changes that sometimes occurred after running One-Click layout. [Q&A 22201]
    Many bugfixes great and small.

Removed Features

    Removed yEd's IconFinder client for importing symbols into user-defined palette sections. IconFinder no longer offers the service interface required for this feature.
    Removed the HTML Flash Viewer and SWF export formats. Both formats relied on Adobe™ Flash™ and thus could not be used as intended anymore.

yEd 3.20.1 - Changes Since 3.20
Security fixes

The new version includes fixes to a set of vulnerabilities, kindly reported by Dawid Czarnecki from NATO Cyber Security Centre (NCSC).

    Fixed XML External Entity injection that could be exploited when opening XML files (including GraphML). [CVE-2020-25215]
    Fixed code execution through XSL transformation when opening XML files together with custom stylesheets. [CVE-2020-25216]

Improvements

    yEd's icon set has been updated to modern SVG icons. Aside from looking great, these icons scale nicely on HDPI devices.
    Added support for additional labels in UML class nodes. [Q&A 17711]

Bugfixes

    Custom window layouts are now properly restored when restarting yEd. [Q&A 4627], [Q&A 7384], [Q&A 18580]
    Many bugfixes great and small.

yEd 3.20 - Changes Since 3.19.1.1
General

    The JREs that come with the Windows installers have been updated to OpenJDK 13.0.2.
    The JREs that come with the Linux and macOS installers have been updated to OpenJDK 14.0.1.

New Features

    Added new Generic Curve Routing algorithm for routing edges.
    Added new Generic Edge Bundling algorithm for routing edges.
    Added new page rank algorithm for calculating centrality measures.

Improvements

    Added SHIFT+F2 (Windows/Linux) and SHIFT+ENTER (macOS) keyboard shortcuts for yEd's 'Add Label' action.
    Improved the initial position for additional labels.

Bugfixes

    Added input validation for many settings dialogs used for layout algorithms to prevent invalid values (such as e.g. negative distances) and subsequent algorithm errors.
    Fixed problems with incorrect additional white space in label texts when opening GraphML files with yEd running on Java 14. [Q&A 13283]
    Fixed problems with custom graph properties names 'url' or 'description' when working with multiple documents. [Q&A 16802]
    Fixed copy-pasting of "Edge Opposite: Dynamic" node label placement policy. [Q&A 15869]
    Many bugfixes great and small.

yEd 3.19.1.1 - Changes Since 3.19.1
General

    The JREs that come with the Windows and Linux installers have been updated to OpenJDK Java 13.0.1.

Improvements

    Improved and corrected import support for the GraphML file format variants of our commercial yFiles diagramming libraries yFiles for Java 3.x, yFiles for JavaFX, yFiles.NET, yFiles WPF, and yFiles for HTML.

Bugfixes

    Fixed problems with template mappings in yEd's properties mapper.[Q&A 16120]

yEd 3.19.1 - Changes Since 3.19
General

    The JREs that come with the Windows and Linux installers have been updated to OpenJDK Java 13.

Bugfixes

    Fixed lots of problems with printers on Windows by upgrading to Java 13.
    Fixed GraphML serialization of Unicode surrogate code units.[Q&A 14542]
    Fixed "No Color" entry for "Line Color" property of edges.[Q&A 14614]
    Fixed duplication of "Edge Opposite: Dynamic" node label placement policy when using the "Duplicate" action. [Q&A 15869]
    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.19 - Changes Since 3.18.2
General

    The JREs that come with the Windows and Linux installers have been updated to OpenJDK Java 11.0.2.

Improvements

    Improved support for display scaling on Windows operating systems.
    Added support for importing GEDCOM NAME sub-tags. [Q&A 14302]

Bugfixes

    Fixed lots of problems with printers on Windows by upgrading to Java 11.
    Fixed problems with the "Paste from System Clipboard" action on Linux operating systems.
    Fixed problems with CTRL+C/V/X shortcuts not working in textfields. [Q&A 14232]
    Fixed adding columns and rows to table nodes without insets. [Q&A 14285]
    Fixed incorrect selection results when using the "Data Property" criterion in the "Select Elements" tool. [Q&A 14201]
    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.18.2 - Changes Since 3.18.1.1
General

    Added action for pasting images from the system clipboard into yEd's editor area.
    Added context menus for copy/cut/paste operations to multi-line text fields.

Bugfixes

    Fixed problems with printers that support several different print resolutions on Windows.
    Added several print preview corrections.
    Fixed color chooser alpha channel support for Java 9 and newer.
    Many bugfixes and improvements in yEd's layout algorithms.

yEd 3.18.1.1 - Changes Since 3.18.1
Bugfixes

    Fixed 'NoSuchMethodError: <init>' problems that prevented yEd from starting on some Windows machines.[Q&A 13631]
    Many bugfixes in yEd's layout algorithms.

General

    The JREs that come with the Windows, macOS, and Linux installers have been updated to Java 10.0.2.
    Additionally, Windows and Linux installers with embedded Java 8 runtime environments are available again for people experiencing problems with Java 10.

yEd 3.18.1 - Changes Since 3.18.0.2
General

    The JREs that come with the Windows, macOS, and Linux installers have been updated to Java 10.0.1. Thus, the installer based versions of yEd require a 64-bit Windows/Linux operating system or Mac OS X 10.10 (Yosemite) to run.
    The zipped yEd Jar file may still be run on 32-bit Windows/Linux operating systems and Mac OS X 10.8/10.9 with an installed Java 8 JRE.

New Features

    Added new layout algorithm for Systems Biology Graphical Notation (SBGN) diagrams.

Improvements

    Added support for display scaling on Windows operating systems.

Bugfixes

    Addressed issues that could happen with the platform-native file chooser dialog on macOS and Linux.
    Many bugfixes, great and small.

yEd 3.18.0.2 - Changes Since 3.18.0.1
Bugfixes

    Fixed an exception that happened when calling the Tree Map layout algorithm on an empty graph.

yEd 3.18.0.1 - Changes Since 3.18
Bugfixes

    Addressed issues that could happen with the platform-native file chooser dialog on macOS and Linux.

yEd 3.18 - Changes Since 3.17.2
New Features

    Added new Tree Map layout algorithm that makes it easy to generate tree maps.

Improvements

    Many improvements of the One-Click Layout.
    yEd now uses the platform-native file chooser dialog on Windows, macOS, and Linux to improve the platform-specific user experience.
    The JREs that are installed by the Windows, macOS, and Linux installers have been updated to Java 1.8.0_162.

Bugfixes

    Many bugfixes, great and small.

yEd 3.17.2 - Changes Since 3.17.1
New Features

    Added new substructure support to the orthogonal layout algorithm.
    Added new swimlane layout algorithm for strictly tabular arrangements (see 'Layout' -> 'Swimlane' -> 'Tabular').

Improvements

    Improved and corrected import support for the GraphML file format variant used by yEd Live.

Bugfixes

    Added fix for missing menu bar on macOS High Sierra 10.13. [Q&A 11986]
    Added fix for excessive whitespace in label texts when running yEd on Java 9.[Q&A 12235]
    Many bugfixes, great and small.

yEd 3.17.1 - Changes Since 3.17
New Features

    Added new palette section for Systems Biology Graphical Notation (SBGN) glyphs. Additionally, added new arrow styles to support SBGN's 'catalysis' and 'necessary stimulation' arcs.

Improvements

    Improved and corrected import support for the GraphML file format variants of our commercial yFiles diagramming libraries yFiles for Java 3.x, yFiles for JavaFX, yFiles.NET, yFiles WPF, and yFiles for HTML.
    Improved the "Fit Node to Label" tool and the "Dynamically Adjust Node Size to Label Size" option with regards to resizing 'Entity with Attribute' nodes from the 'Entity Relationship' palette section and 'Class' nodes from the 'UML' palette section. [Q&A 7920], [Q&A 11651]

Bugfixes

    Added fix for crashes when opening a load or save file dialog on Windows 10 with Creator's Update installed. [Q&A 10681]
    Many bugfixes, great and small.