py-virtualenv20: Update to 20.13.0
Features - 20.13.0

* Add downloaded wheel information in the relevant JSON embed file to
prevent additional downloads of the same wheel.

Bugfixes - 20.13.0

* Fix AttributeError: 'bool' object has no attribute 'error' when creating
a Python 2.x virtualenv on macOS
* Fix PermissionError: [Errno 1] Operation not permitted when creating a
Python 2.x virtualenv on macOS/arm64