p5-MongoDB: update to 2.0.1.
Still lots of dependencies missing.

v2.0.1    2018-07-10 18:05:38-04:00 America/New_York

  [Additions]

    - PERL-897 'nameOnly' option added to 'list_collections' for efficiency

  [Bug Fixes]

    - PERL-953 Suppress warnings when using compression without
      specifying a compression level.

    - PERL-959 Undefer constructor in the private constructor to ensure
      cursors are cleaned up on destructions.

  [Documentation]

    - PERL-952 Show how to upgrade v2 over v1 while avoiding shadows

    - PERL-967 Document more clearlly that X509 doesn't need a 'username'
      parameters, as the username is extracted from the certificate.

    - PERL-968 Fix various spelling errors

  [Prerequisites]

    - PERL-958 BSON::XS not available on Windows before Vista

    - Bumped BSON.pm prereq to v1.6.6 for a BSON::Timestamp bug fix

v2.0.0    2018-06-26 14:55:50-04:00 America/New_York

  [!!! Incompatible Changes !!!]

    - PERL-640 Remove bundled MongoDB::BSON codec and use BSON.pm and/or
      BSON::XS instead. While this is a sweeping change, applications that
      relied on the default encoder are likely to need minimal changes.
      MongoDB type wrapper classes will encode correctly, but decoded
      wrappers will be from the BSON.pm library instead.  See
      MongoDB::Upgrading for more details.  Additionally, with this change,
      the MongoDB driver can now be used without a compiler.

    - PERL-742 Require Perl 5.10.1 or later

    - PERL-871 Remove features and methods deprecated in v1.0.0

  [*** Deprecations ***]

    - PERL-718 Deprecate find option 'modifiers'

    - PERL-856 Deprecate 'md5' field in GridFS file documents

    - PERL-872 Deprecate maxScan find option

    - PERL-873 Deprecate cursor snapshot option

    - PERL-926 Deprecate 'count' method

  [Additions]

    - PERL-710 Support authSource URI option

    - PERL-718 Add find options to replace deprecated 'modifiers' option

    - PERL-768 Added support for aggregation hints

    - PERL-778 Add support for wire protocol compression

    - PERL-782 Add maxTimeMS option to Indexview methods

    - PERL-787 Implement arrayFilters support

    - PERL-790 Implement Drivers Sessions API

    - PERL-791 Change stream support

    - PERL-792 Implement Retryable Writes

    - PERL-793 Causally Consistency read support

    - PERL-805 Implement database enumeration spec

    - PERL-807 Implement DNS Seedlist Discovery (mongodb+srv://...)

    - PERL-808 Add support for aggregation comment option

    - PERL-863 Implement SCRAM-SHA-256 authentication

    - PERL-875 Multi-document ACID transactions (replica sets only)

    - PERL-883 Implement command monitoring

    - PERL-912 Add 'watch' methods to MongoDB::Database and
      MongoDB::MongoClient

    - PERL-940 Added 'startAtOperationTime' option to 'watch' methods

    - PERL-944 Add 'client' method to MongoDB::Database

  [Bug fixes]

    - PERL-690 Fix undefined reference to strerror_r on Windows

    - PERL-781 Prevent index drop errors for no collection

    - PERL-783 Check username/password are URI-escaped

    - PERL-865 Fix wide character error in auth

    - PERL-887 Fix topology_status with refresh

    - PERL-891 Fix bugs found during command monitoring testing (bulk_write
      write concern, query limit propagation, cursor internal accounting)

    - PERL-936 Added session support to 'watch' for MongoDB::Collection

    - PERL-948 Refactor op dispatching to avoid introducing circular refs
      in session management

  [Changes]

    - PERL-641 Make legacy typewrappers into subclasses of BSON.pm classes

    - PERL-733 Require ordered document for run_command

    - PERL-794 Improve resolution of GridFS uploadDate

    - PERL-816 Improve error message for incompatible MongoDB versions

    - PERL-864 Improve auth error messages

  [Documentation]

    - PERL-768 Document GridFS uniqueness constraints

    - PERL-788 Amend MongoDB::Cursor docs

    - PERL-809 Added t/examples/changestream.t

    - PERL-859 Added tests with example code for MongoDB's docs site

    - PERL-859 Add test examples for aggregate, run_command and indexing

    - PERL-866 Document how to use the latest TLS protocols

    - PERL-903 Revise MongoDB::DataTypes and MongoDB::Tutorial

    - PERL-908 Add transaction examples for docs

    - PERL-917 Fix minor spelling error

  [Prerequisites]

    - PERL-900 Conditionally require XS dependencies (BSON::XS,
      Class::XSAccessor and Type::Tiny::XS)

    - PERL-934 Bumped Authen::SCRAM prerequisite to work around
      deep dependency issues

    - PERL-941 Bump BSON prereq to v1.6.5 for BSON::Time fix on 32-bit perls

    - PERL-947 Require Authen::SCRAM 0.011 to avoid memory leak

  [Removals]

    - PERL-765 Remove DateTime from driver code and tests

  [Testing]

    - PERL-668 Update SDAM spec tests

    - PERL-671 Update CRUD testing data files

    - PERL-700 Fix app_name test for multi-shard topologies

    - PERL-719 Resync CRUD spec tests

    - PERL-726 Update deprecated 'last_error' test

    - PERL-727 Fix GridFS tests on Windows

    - PERL-907 Test with BSON Codec using full wrapping

    - PERL-951 Make await cursor test more robust

  [~ Internal changes ~]

    - PERL-666 Eliminate Module::Install in Makefile.PL

    - PERL-715 Force localhost to connect via IPv4

    - PERL-767 Cache SCRAM-SHA-1 client key

    - PERL-826 Stop sending maxAwaitTimeMS if not set

    - PERL-900 Vendor ExtUtils::HasCompiler

    - PERL-937 Gossip cluster time during SDAM

v1.999.1  2018-06-23 23:41:05-04:00 America/New_York (TRIAL RELEASE)

v1.999.0  2018-06-15 12:38:56-04:00 America/New_York (TRIAL RELEASE)

v1.8.3    2018-06-25 12:20:13-04:00 America/New_York

  [Bug fixes]

  - PERL-923 Fix user/password percent encoding validation

v1.8.2    2018-05-22 12:24:02-04:00 America/New_York

  [Bug fixes]

  - PERL-870  Repeated credential validation may skip validation after
    first failure

  - PERL-878 - Update Authen::SCRAM prereq to fix unicode bug

  - PERL-879 - Deprecate snapshot option

  - PERL-882 - Document how to use the latest TLS protocols

  - PERL-906 - Work around new version of Type::Tiny::XS with a stricter
    definition of type Bool