compiler-rt-netbsd: Install compiler-rt files into subdir of clang
This is required to get clang find the files out-of-the box.

Tested on NetBSD.

This command:
/usr/pkg/bin/clang -fno-omit-frame-pointer -O0 -g -ggdb -U_FORTIFY_SOURCE -fsanitize=address -lasan test.c

Started to find the libraries and print new kind of errors, this time about
unrecognized symbols. For example:

/usr/pkg/lib/clang/5.0.0/lib/netbsd8.99/libclang_rt.asan-x86_64.a(asan_allocator.cc.o): In function `__sanitizer::SizeClassAllocator64<__asan::AP64>::PrintStats()':
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_primary64.h:254: undefined reference to `__sanitizer::GetMemoryProfile(void (*)(unsigned long, unsigned long, bool, unsigned long*, unsigned long), unsigned long*, unsigned long)'
/usr/pkg/lib/clang/5.0.0/lib/netbsd8.99/libclang_rt.asan-x86_64.a(asan_interceptors.cc.o): In function `ioctl_common_pre':
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_ioctl.inc:584: undefined reference to `__sanitizer::IOCTL_SIOCGIFCONF'
/usr/pkg/lib/clang/5.0.0/lib/netbsd8.99/libclang_rt.asan-x86_64.a(asan_interceptors.cc.o): In function `ioctl_common_post':
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors_ioctl.inc:600: undefined reference to `__sanitizer::IOCTL_SIOCGIFCONF'
/usr/pkg/lib/clang/5.0.0/lib/netbsd8.99/libclang_rt.asan-x86_64.a(asan_interceptors.cc.o): In function `__interceptor_getitimer':
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2028: undefined reference to `__sanitizer::struct_itimerval_sz'
/usr/pkg/lib/clang/5.0.0/lib/netbsd8.99/libclang_rt.asan-x86_64.a(asan_interceptors.cc.o): In function `__interceptor_setitimer':
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2036: undefined reference to `__sanitizer::struct_itimerval_sz'
/tmp/pkgsrc-tmp/wip/compiler-rt-netbsd/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:2042: undefined reference to `__sanitizer::struct_itimerval_sz'

Sponsored by <The NetBSD Foundation>