espeak: Avoid narrowing conversion errors
With at least gcc-6.4.0 the build failed due:

 | tr_languages.cpp:201:43: error: narrowing conversion of '194' from 'int' to 'char' inside { } [-Wnarrowing]
 |  const char string_ordinal[] = {0xc2,0xba,0};  // masculine ordinal character, UTF-8
 |                                            ^

Use wchar_t instead of char to avoid that.