libre: update to re-2.6.0
v2.6.0

What's Changed

  • ice: change one warning to notice by @alfredh in #421
  • Fix compilation error on musl: __GNUC_PREREQ macro defined only
    for libc library by @widgetii in #422
  • sip: add RFC 3262 support by @maximilianfridrich in #419
  • bfcp: Add support for TCP transport for BFCP by @Lastique in #411
  • strans/accept: fix cancel/rejection by @maximilianfridrich in #423
  • hash: add hash_list_idx() by @sreimers in #427
  • tls: Add a method to set OpenSSL certificate by @Lastique in #426
  * sipsess: fix PRACK offer/answer behavior by @maximilianfridrich
    in #430
  * thread: thrd_error fixes by @sreimers in #431
  * sipsess: fix coverity warnings by @maximilianfridrich in #433
  * main: add re_nfds() and poll_method_get() getters by @sreimers
    in #435
  * fmt/print: fix local_itoa casting by @sreimers in #437
  * leb128: switch to uint64_t by @alfredh in #436
  * types,mk: remove HAVE_STDBOOL_H by @sreimers in #439
  * fmt/print: snprintf restrict declarations by @sreimers in #438
  * net: minor cleanup in linux route code by @alfredh in #440
  * sip: add RFC 3311 support by @maximilianfridrich in #425
  * rtmp: check upper bound for amf array by @alfredh in #441
  * rtcp: check TWCC count range (Coverity fix) by @alfredh in #442
  * mem: Align data to natural alignment by @Lastique in #416
  * ci/misc: bump pr-dependency-action@v0.5 by @sreimers in #444
  * net: linux/rt: init gw to correct af by @alfredh in #447
  * rtp: Add rtcp_send declaration to the public header by @Lastique
    in #448
  * Main method best by @alfredh in #449
  * cmake: add explicit /volatile:ms (required for arm) by @sreimers
    in #451
  * mem: Make nrefs atomic by @Lastique in #446
  * atomic: add some short atomic alias helpers by @sreimers in #452
  * ci/build: replace deprecated macos-10.15 by @sreimers in #454
  * Improve RFC 3262 by @maximilianfridrich in #450
  * atomic: rename helpers by @sreimers in #455
  * cmake,make: add clang atomic-implicit-seq-cst warning by
    @sreimers in #453
  * cmake: add missing includes to install by @paresy in #456
  * Fix prack handling by @maximilianfridrich in #457
  * mem: Correct memory clobbering size by @Lastique in #458
  * mem: Correct calculation of total mem size in mem_status by
    @Lastique in #459
  * tls: Securely clear memory from private key material by
    @Lastique in #460
  * fmt/str_error: always print error number by @sreimers in #461
  * thread: add cnd_broadcast posix/win32 fallbacks by @sreimers in
    #463
  * list: add list_move() helper by @sreimers in #464
  * thread: fix thread_create_name ENOMEM by @sreimers in #465