Update spotifyd to 0.3.0
Important, you'll like hit this [upstream issue][1] and see something
like:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Error { inner: ErrorInner { kind: Custom, line: Some(64), col: 17, at:
Some(1937), message: "invalid type: integer `90`, expected a string",
key: ["global", "initial_volume"] } }', src/config.rs:468:67
note: run with `RUST_BACKTRACE=1` environment variable to display a
backtrace
```

This is due to the config format changing and values needing quoting.

Adds a new patch [based on this PR][2].

[1]: https://github.com/Spotifyd/spotifyd/issues/765
[2]: https://github.com/Spotifyd/spotifyd/pull/796