librsvg: upgrade candidate to 2.52.6
=> Checking for missing run-time search paths in librsvg-2.52.6
ERROR: bin/rsvg-convert: missing library: libgobject-2.0.so.0
ERROR: bin/rsvg-convert: missing library: libcairo.so.2
ERROR: bin/rsvg-convert: missing library: libpangocairo-1.0.so.0
ERROR: bin/rsvg-convert: missing library: libgio-2.0.so.0
ERROR: bin/rsvg-convert: missing library: libgdk_pixbuf-2.0.so.0
ERROR: bin/rsvg-convert: missing library: libglib-2.0.so.0
ERROR: bin/rsvg-convert: missing library: libcairo-gobject.so.2
ERROR: bin/rsvg-convert: missing library: libxml2.so.2
ERROR: bin/rsvg-convert: missing library: libpango-1.0.so.0
*** Error code 1