plan9port: add more logic to install
Move everything to the ${DESTDIR}/${PREFIX}/plan9 and then install from there.

Checks still fails due:

 => Checking for missing run-time search paths in plan9port-20200622
 ERROR: plan9/bin/xshove: missing library: libX11.so.7

There are several hardcoded assumptions that probably needs to be addressed
(e.g. honoring {C,LD}FLAGS, X11BASE and maybe something else too!)