mailman3: Update to 3.1.1.
Bugs
----
- An AttributeError: 'str' object has no attribute 'decode'
  exception in subject prefixing is fixed.
- Syntactically invalid sender addresses are now ignored.
- Messages with no syntactically valid senders are now automatically
  discarded.
- Generated ``regexp`` tables for Postfix now account for possible
  ``+extra`` additions to the ``-bounces`` and ``-confirm`` addresses.
- A list whose name is one of the ``admin``, ``bounces``, ``confirm``,
  etc. subaddresses can now be posted to.
- Various message holds and rejects that gave 'N/A' as a reason now
  give an appropriate reason.
- A missing html_to_plain_text_command is now properly detected and
  logged.
- Bounce messages are now composed for proper translations.

Configuration
-------------
- Mailman now also searches at ``/etc/mailman3/mailman.cfg`` for the
  configuration file.

Interfaces
----------
- A new template ``list:user:notice:rejected`` has been added for
  customizing the bounce message rejection notice.

REST
----
- Allow a mailing list's acceptable aliases to be cleared by calling
  ``DELETE`` on the list's ``config/acceptable_aliases`` resource.