py-llvm-lit-netbsd: Switch to egg.mk
Switch
 .include "../../lang/python/distutils.mk"
 .include "../../lang/python/application.mk"

To
 .include "../../lang/python/egg.mk"

This option works better in pristime build.

The older version failed with:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Sponsored by <The NetBSD Foundation>