sparse: add some patches to be useful for netbsd
it keeps spewing:
error: Expected ) in function declarator
error: got ,

or:
error: got "GCC visibility push(default)"

if we tolerate more warnings and errors, it can
be filtered out later on.

one patch from pkgsrc itself.

describe patch for not dying on missing includes