alacritty: add two missing build dependencies
Both were actively requested by the package in an empty sandbox.

Now it fails with:

error[E0433]: failed to resolve: use of undeclared type or module `x11_dl`
   --> alacritty_terminal/src/window.rs:428:13
    |
428 |         use x11_dl::xlib::{self, PropModeReplace, XA_CARDINAL};
    |             ^^^^^^ use of undeclared type or module `x11_dl`

error[E0432]: unresolved import `x11_dl`
   --> alacritty_terminal/src/window.rs:428:13
    |
428 |         use x11_dl::xlib::{self, PropModeReplace, XA_CARDINAL};
    |             ^^^^^^ use of undeclared type or module `x11_dl`

error[E0425]: cannot find value `XA_CARDINAL` in this scope
   --> alacritty_terminal/src/window.rs:446:21
    |
446 |                     XA_CARDINAL,
    |                     ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `PropModeReplace` in this scope
   --> alacritty_terminal/src/window.rs:448:21
    |
448 |                     PropModeReplace,
    |                     ^^^^^^^^^^^^^^^ not found in this scope

warning: unused imports: `PropModeReplace`, `XA_CARDINAL`
   --> alacritty_terminal/src/window.rs:428:34
    |
428 |         use x11_dl::xlib::{self, PropModeReplace, XA_CARDINAL};
    |                                  ^^^^^^^^^^^^^^^  ^^^^^^^^^^^
    |
    = note: #[warn(unused_imports)] on by default

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.