rust-beta: update to 1.98.0-beta.5
Currently it doesn't build due to warning = error.

===> Building for rust-1.98.0beta.5
Building bootstrap
warning: linker stderr: ld: /usr/pkgsrc/wip/rust-beta/work/rustc-beta-src/build/bootstrap/debug/deps/librustix-095bb558e8cb6f26.rlib(rustix-095bb558e8cb6f26.rustix.b0b38a2615679391-cgu.1.rcgu.o): in function `rustix::backend::io::syscalls::dup3':
         rustix.b0b38a2615679391-cgu.1:(.text._RNvNtNtNtCsfazM32Pycft_6rustix7backend2io8syscalls4dup3+0x44): warning: reference to compatibility dup3(); include <unistd.h> to generate correct reference
         ld: /usr/pkgsrc/wip/rust-beta/work/rustc-beta-src/build/bootstrap/debug/deps/librustix-095bb558e8cb6f26.rlib(rustix-095bb558e8cb6f26.rustix.b0b38a2615679391-cgu.2.rcgu.o): in function `rustix::backend::fs::syscalls::fstatvfs':
         rustix.b0b38a2615679391-cgu.2:(.text._RNvNtNtNtCsfazM32Pycft_6rustix7backend2fs8syscalls8fstatvfs+0x39): warning: reference to compatibility fstatvfs(); include <sys/statvfs.h> to generate correct reference
  |
  = note: `#[warn(linker_messages)]` on by default

warning: linker stdout: ld: /usr/pkgsrc/wip/rust-beta/work/rustc-beta-src/build/bootstrap/debug/deps/librustix-095bb558e8cb6f26.rlib(rustix-095bb558e8cb6f26.rustix.b0b38a2615679391-cgu.1.rcgu.o): note: the message above does not take linker garbage collection into account
         ld: /usr/pkgsrc/wip/rust-beta/work/rustc-beta-src/build/bootstrap/debug/deps/librustix-095bb558e8cb6f26.rlib(rustix-095bb558e8cb6f26.rustix.b0b38a2615679391-cgu.2.rcgu.o): note: the message above does not take linker garbage collection into account

error: `bootstrap` (bin "rustdoc") generated 2 warnings
error: warnings are denied by `build.warnings` configuration
warning: build failed, waiting for other jobs to finish...
error: `bootstrap` (bin "rustc") generated 2 warnings (2 duplicates)
error: warnings are denied by `build.warnings` configuration
failed to run: /usr/pkgsrc/wip/rust-beta/work/rust-bootstrap/bin/cargo build --jobs=default --manifest-path /usr/pkgsrc/wip/rust-beta/work/rustc-beta-src/src/bootstrap/Cargo.toml -Zroot-dir=/usr/pkgsrc/wip/rust-beta/work/rustc-beta-src --frozen
Build completed unsuccessfully in 0:00:02