wip/thunderbird: draft & unsuccessful update to 115.1.1.
Still does not build, for me the build bombs out with

ld: ../../../toolkit/library/build/libxul.so: undefined reference to `ld: ../../toolkit/library/build/libxul.so: undefined reference to `malloc_usable_sizemalloc_usable_size'

(error message looks weird, name repeated...)

See TODO for more information.

Remove old patches in main directory, and adapt as best as
possible to the fact that thunderbird changed to a python-based
configure, so no more autoconf.