ChangeLog:
ng0 (29 Apr 2019)
- Fix the failing build
- Revert "Use gnunet standard .dir-locals.el for configuring emacs."
  This reverts commit dc6e99afc8715690635cca2f431190d87ef885eb.
Hartmut Goebel (18 Apr 2019)
- Use gnunet standard .dir-locals.el for configuring emacs.
ng0 (12 Apr 2019)
- gssapi
- docs.
- include
- Properly enforce building with the right configure switches.
  The downside of this commit is that to address the wrong
  package definitions out there, I have to break with the
  good package definitions.
- Merge tag 'curl-7_64_1' of https://github.com/curl/curl
  7.64.1

curl ChangeLog:
Changes:
    alt-svc: experiemental support added
    configure: add --with-amissl
Bugfixes:
    AppVeyor: add MinGW-w64 and classic Mingw builds
    AppVeyor: switch VS 2015 builds to VS 2017 image
    CURLU: fix NULL dereference when used over proxy
    Curl_easy: remove req.maxfd - never used!
    Curl_now: figure out windows version in win32_init:
    Curl_resolv: fix a gcc -Werror=maybe-uninitialized warning
    DoH: inherit some SSL options from user's easy handle
    Secure Transport: no more "darwinssl"
    Secure Transport: tvOS 11 is required for ALPN support
    cirrus: Added FreeBSD builds using Cirrus CI
    cleanup: make local functions static
    cli tool: do not use mime.h private structures
    cmdline-opts/proxytunnel.d: the option tunnnels all protocols
    configure: add additional libraries to check for LDAP support
    configure: remove the unused fdopen macro
    configure: show features as well in the final summary
    conncache: use conn->data to know if a transfer owns it
    connection: never reuse CONNECT_ONLY connections
    connection_check: restore original conn->data after the check
    connection_check: set ->data to the transfer doing the check
    cookie: Add support for cookie prefixes
    cookies: dotless names can set cookies again
    cookies: fix NULL dereference if flushing cookies with no CookieInfo set
    curl.1: --user and --proxy-user are hidden from ps output
    curl.1: mark the argument to --cookie as
    curl.h: use __has_declspec_attribute for shared builds
    curl: display --version features sorted alphabetically
    curl: fix FreeBSD compiler warning in the --xattr code
    curl: remove MANUAL from -M output
    curl_easy_duphandle.3: clarify that a duped handle has no shares
    curl_multi_remove_handle.3: use at any time, just not from within callbacks
    curl_url.3: this API is not experimental anymore
    dns: release sharelock as soon as possible
    docs: update max-redirs.d phrasing
    easy: fix win32 init to work without CURL_GLOBAL_WIN32
    examples/10-at-a-time.c: improve readability and simplify
    examples/cacertinmem.c: use multiple certificates for loading CA-chain
    examples/crawler: Fix the Accept-Encoding setting
    examples/ephiperfifo.c: various fixes
    examples/externalsocket: add missing close socket calls
    examples/http2-download: cleaned up
    examples/http2-serverpush: add some sensible error checks
    examples/http2-upload: cleaned up
    examples/httpcustomheader: Value stored to 'res' is never read
    examples/postinmemory: Potential leak of memory pointed to by 'chunk.memory'
    examples/sftpuploadresume: Value stored to 'result' is never read
    examples: only include
    examples: remove recursive calls to curl_multi_socket_action
    examples: remove superfluous null-pointer checks
    file: fix "Checking if unsigned variable 'readcount' is less than zero."
    fnmatch: disable if FTP is disabled
    gnutls: remove call to deprecated gnutls_compression_get_name
    gopher: remove check for path == NULL
    gssapi: fix deprecated header warnings
    hostip: make create_hostcache_id avoid alloc + free
    http2: multi_connchanged() moved from multi.c, only used for h2
    http2: verify :athority in push promise requests
    http: make adding a blank header thread-safe
    http: send payload when (proxy) authentication is done
    http: set state.infilesize when sending multipart formposts
    makefile: make checksrc and hugefile commands "silent"
    mbedtls: make it build even if MBEDTLS_VERSION_C isn't set
    mbedtls: release sessionid resources on error
    memdebug: log pointer before freeing its data
    memdebug: make debug-specific functions use curl_dbg_ prefix
    mime: put the boundary buffer into the curl_mime struct
    multi: call multi_done on connect timeouts, fixes CURLINFO_TOTAL_TIME
    multi: remove verbose "Expire in" ... messages
    multi: removed unused code for request retries
    multi: support verbose conncache closure handle
    negotiate: fix for HTTP POST with Negotiate
    openssl: add support for TLS ASYNC state
    openssl: if cert type is ENG and no key specified, key is ENG too
    pretransfer: don't strlen() POSTFIELDS set for GET requests
    rand: Fix a mismatch between comments in source and header
    runtests: detect "schannel" as an alias for "winssl"
    schannel: be quiet - remove verbose output
    schannel: close TLS before removing conn from cache
    schannel: support CALG_ECDH_EPHEM algorithm
    scripts/completion.pl: also generate fish completion file
    singlesocket: fix the 'sincebefore' placement
    source: fix two 'nread' may be used uninitialized warnings
    ssh: fix Condition '!status' is always true
    ssh: loop the state machine if not done and not blocking
    strerror: make the strerror function use local buffers
    system_win32: move win32_init here from easy.c
    test578: make it read data from the correct test
    tests: Fixed XML validation errors in some test files
    tests: add stderr comparison to the test suite
    tests: fix multiple may be used uninitialized warnings
    threaded-resolver: shutdown the resolver thread without error message
    tool_cb_wrt: fix writing to Windows null device NUL
    tool_getpass: termios.h is present on AmigaOS 3, but no tcgetattr/tcsetattr
    tool_operate: build on AmigaOS
    tool_operate: fix typecheck warning
    transfer.c: do not compute length of undefined hex buffer
    travis: add build using gnutls
    travis: add scan-build
    travis: bump the used wolfSSL version to 4.0.0
    travis: enable valgrind for the iconv tests
    travis: use updated compiler versions: clang 7 and gcc 8
    unit1307: require FTP support
    unit1651: survive curl_easy_init() fails
    url/idnconvert: remove scan for <= 32 ascii values
    url: change conn shutdown order to ensure SOCKETFUNCTION callbacks
    urlapi: reduce variable scope, remove unreachable 'break'
    urldata: convert bools to bitfields and move to end
    urldata: simplify bytecounters
    urlglob: Argument with 'nonnull' attribute passed null
    version.c: silent scan-build even when librtmp is not enabled
    vtls: rename some of the SSL functions
    wolfssl: stop custom-adding curves
    x509asn1: "Dereference of null pointer"
    x509asn1: cleanup and unify code layout
    zsh.pl: escape ':' character
    zsh.pl: update regex to better match curl -h output