Revert "(www/webkit-gtk) Candidate for 2.45.3, but configure error now"
2.36.8 compile problem     (*1)
2.36.5 the same as above
2.45.3 configure problem (Epoxy:Epoxy)

(*)
ImageDecoderGStreamer.cpp:278:5: error: braces around scalar
initializer for type 'gboolean (*)(GstAppSink*, GstQuery*, gpointer)'
{aka 'int (*)(_GstAppSink*, _GstQuery*, void*)'}
     };

This reverts commit 73f8322ad22739baffb972b7c48f7c77bea9e0f3.