Fix configure phase, mark as not -j ready, remove -ldl on !Linux. Try converting to user-destdir; however, the package doesn't link for me: AudioOpenAL.o: In function `AudioOpenAL::loadSounds()': AudioOpenAL.cpp:(.text+0x5f6): undefined reference to `alutLoadWAV'