Revert "lldb: needs readline"
The error is:
[  1%] Python script building LLDB Python wrapper
... /scripts/Python/modules/readline/readline.cpp:9:31: fatal error: editline/readline.h: No such file or directory
compilation terminated.

XXX not really sure what is going on here. Maybe it needs py27-readline.
This reverts commit c62d5a884b46165308e7c129cf9c05748f42dc9f.