Import swift-2.0nb20140818 as wip/swift-git.
Swift is trying to plug a hole in the XMPP client landscape, and has
these aims:

    * Wide platform availability.
    * Doing the "Right Thing" for the user, without configuration.
    * Doing the "Right Thing" with standards-compliance.
    * Targeting the end-users, not the system administrators.
    * Being an XMPP client - not multi-protocol.
    * Concentrating on the most frequently performed tasks.
    * Never interrupt the user with something that doesn't need attention.

Features of interest

    * Easy status setting.
    * Easy room joining and bookmarking.
    * XEP-0258 Labelling for secure environments.
    * Stream compression for bandwidth-saving.
    * Support for the new SCRAM authentication mechanism.

This package contains the current development version from the git
repository.

TODO:
Doesn't link with boost-1.56:
Swiften/libSwiften.a(CombinedAvatarProvider.o): In function `Swift::CombinedAvatarProvider::handleAvatarChanged(Swift::JID const&)':
work/swift/Swiften/Avatars/CombinedAvatarProvider.cpp:43: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, std::string>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<std::string> const&)'
Swiften/libSwiften.a(CombinedAvatarProvider.o): In function `Swift::CombinedAvatarProvider::getCombinedAvatarAndCache(Swift::JID const&) const':
work/swift/Swiften/Avatars/CombinedAvatarProvider.cpp:53: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, std::string>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<std::string> const&)'
Swiften/libSwiften.a(StreamResumeSerializer.o): In function `bool boost::detail::lexical_istream_limited_src<char, std::char_traits<char>, true, 2ul>::shl_input_streamable<boost::optional<unsigned int> const>(boost::optional<unsigned int> const&)':
work/.buildlink/include/boost/lexical_cast.hpp:1408: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, unsigned int>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<unsigned int> const&)'