Old tarball not available any longer, update to latest version. However, it doesn't build:
gmake[2]: Entering directory `/scratch/wip/muine/work/muine-0.8.10/src'
MONO_XMLSERIALIZER_THS=no wsdl -namespace:Amazon ./AmazonSearchService.wsdl
Web Services Description Language Utility
Mono Framework v2.0.50727.42
Error: Key duplication when adding: System.Web.Services.Description.MessagePart
Stack:
   at System.Collections.Hashtable.PutImpl (System.Object key, System.Object value, Boolean overwrite) [0x00000]
  at System.Collections.Hashtable.Add (System.Object key, System.Object value) [0x00000]
  at System.Web.Services.Description.BasicProfileChecker.Check (System.Web.Services.Description.ConformanceCheckContext ctx, System.Web.Services.Description.Binding value) [0x00000]
  at System.Web.Services.Description.WebServicesInteroperability.Check (System.Web.Services.Description.ConformanceCheckContext ctx, System.Web.Services.Description.ConformanceChecker checker, System.Web.Services.Description.Binding b) [0x00000]
  at System.Web.Services.Description.WebServicesInteroperability.Check (System.Web.Services.Description.ConformanceCheckContext ctx, System.Web.Services.Description.ConformanceChecker checker, System.Web.Services.Description.ServiceDescription sd) [0x00000]
  at System.Web.Services.Description.WebServicesInteroperability.Check (WsiProfiles claims, System.Web.Services.Description.ConformanceCheckContext ctx, IEnumerable documents) [0x00000]
  at System.Web.Services.Description.WebServicesInteroperability.CheckConformance (WsiProfiles claims, System.Web.Services.Description.WebReference webReference, System.Web.Services.Description.BasicProfileViolationCollection violations) [0x00000]
  at Mono.WebServices.Driver.GenerateCode (System.Web.Services.Description.WebReferenceCollection references, System.CodeDom.CodeCompileUnit codeUnit) [0x00000]
  at Mono.WebServices.Driver.Run (System.String[] args) [0x00000]
gmake[2]: *** [AmazonSearchService.cs] Error 2
gmake[2]: Leaving directory `/scratch/wip/muine/work/muine-0.8.10/src'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/scratch/wip/muine/work/muine-0.8.10'
gmake: *** [all] Error 2