lldb-netbsd: Fixes in the breakpoint session
Fix:
 - kve_path resolving, noted by Christos Zoulas
 - kinfo_getvmmap was called for invalid PID
 - add support for writing registers
 - introduce WriteRegisterSet()

Breakpoints appear to work and the number of passing tests has been doubled:

===================
Test Result Summary
===================
Test Methods:       1240
Reruns:                0
Success:             596
Expected Failure:     21
Failure:              86
Error:                91
Exceptional Exit:      0
Unexpected Success:    1
Skip:                444
Timeout:               1
Expected Timeout:      0

Sponsored by <The NetBSD Foundation>