go-collectd: add a draft package for go-based collectd plugins.
This one is known not to build, ref:

===> Building for go-collectd-0.6.0
collectd.org/plugin/fake
collectd.org/plugin
plugin/fake/write.go:7:11: fatal error: plugin.h: No such file or directory
    7 | // #include "plugin.h"
      |           ^~~~~~~~~~
compilation terminated.
plugin/c.go:7:11: fatal error: plugin.h: No such file or directory
    7 | // #include "plugin.h"
      |           ^~~~~~~~~~
compilation terminated.
*** Error code 1

Possibly due to the go compiler not using the pkgsrc wrapper
for the C compiler invocations.