webkit-gtk: Import webkit-gtk-2.16.1 as wip/webkit-gtk
WebKit is an open source web browser engine. WebKit is also the name of
the Mac OS X system framework version of the engine that's used by
Safari, Dashboard, Mail, and many other OS X applications. WebKit's HTML
and JavaScript code began as a branch of the KHTML and KJS libraries
from KDE.

This is the GTK port of the engine.

XXX: Patches synced but still doesn't build due to (from the TODO):
XXX:
XXX:  [  5%] Linking CXX shared library ../../lib/libjavascriptcoregtk-4.0.so
XXX:  CMakeFiles/JavaScriptCore.dir/runtime/CustomGetterSetter.cpp.o: In function `JSC::callCustomSetter(JSC::ExecState*, JSC::JSValue, bool, JSC::JSObject*, JSC::JSValue, JSC::JSValue)':
XXX:  CustomGetterSetter.cpp:(.text+0x87): undefined reference to `JSC::HeapCell::vm() const'
XXX:  CMakeFiles/JavaScriptCore.dir/runtime/FunctionExecutableDump.cpp.o: In function `JSC::FunctionExecutableDump::dump(WTF::PrintStream&) const':
XXX:  FunctionExecutableDump.cpp:(.text+0x29): undefined reference to `JSC::HeapCell::vm() const'
XXX:  FunctionExecutableDump.cpp:(.text+0x5b): undefined reference to `JSC::HeapCell::vm() const'
XXX:  FunctionExecutableDump.cpp:(.text+0x8c): undefined reference to `JSC::HeapCell::vm() const'
XXX:  FunctionExecutableDump.cpp:(.text+0xbe): undefined reference to `JSC::HeapCell::vm() const'
XXX:  CMakeFiles/JavaScriptCore.dir/runtime/FunctionExecutableDump.cpp.o:FunctionExecutableDump.cpp:(.text+0xef): more undefined references to `JSC::HeapCell::vm() const' follow
XXX:  Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build.make:23840: recipe for target 'lib/libjavascriptcoregtk-4.0.so.18.5.8' failed
XXX:  gmake[2]: *** [lib/libjavascriptcoregtk-4.0.so.18.5.8] Error 1
XXX:  CMakeFiles/Makefile2:369: recipe for target 'Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/all' failed
XXX:  gmake[1]: *** [Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/all] Error 2
XXX:  Makefile:151: recipe for target 'all' failed
XXX:  gmake: *** [all] Error 2