kubo: update to 0.17.0
When building using the pkgsrc infrastructure, this fails with:

===> Building for kubo-0.17.0
github.com/ipfs/kubo/fuse/ipns
fuse/ipns/mount_unix.go:27:15: undefined: NewFileSystem
fuse/ipns/mount_unix.go:32:15: undefined: mount.NewMount
runtime.main_main·f: function main is undeclared in the main package

When building with make (currently implemented this way), the
package downloads all modules during build.